#!/bin/bash
cd /work

git clone https://github.com/fairwaves/osmo-combo
cd osmo-combo
git submodule init
git submodule update
./apply_patches.sh static-build
make

cd /work
# Osmo-TRX
git clone https://github.com/myriadrf/osmo-trx
cd osmo-trx
autoreconf -i
./configure
make
make install

